### ISSUE TITLE
Fix Pip installed package bug

### ISSUE THREAD

**Issue by YuanmingLeee** [MLSysOps/MIGProfiler#29]
Cannot use `migperf` package:
```
#! pip install migperf
import MIGProfiler    # this is weird
vars(MIGProfiler)
# output:
# {'__name__': 'MIGProfiler', '__doc__': None, '__package__': 'MIGProfiler', '__loader__': <_frozen_importlib_external._NamespaceLoader object at 0x7f9e0c7596a0>, '__spec__': ModuleSpec(name='MIGProfiler', loader=<_frozen_importlib_external._NamespaceLoader object at 0x7f9e0c7596a0>, submodule_search_locations=_NamespacePath(['/root/workspace/MIGProfiler'])), '__file__': None, '__path__': _NamespacePath(['/root/workspace/MIGProfiler'])}
```
1. weird naming
2. no sub-module found

**Comment by dixing0908** [comment]
we need to design a python api like:
> import migperf
> migperf.profile()
> mig.export()
before we pack it up in pip install. So the current pip install is only for quick requirements preparing rather than a python package. 
For now migperf can only be executed by python in shell. Do you think that we should expand the migperf usage in python api?

**Comment by YuanmingLeee** [comment]
I will make the installed package looks normal and accessible to all current sub-modules first.
